# Generated by Django 6.0.4 on 2026-04-23 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('carrier_name', models.CharField(max_length=200)),
                ('abuse_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resporg',
            },
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('landing_url', models.URLField(blank=True)),
                ('resporg_raw', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reported', 'Reported'), ('killed', 'Killed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ftc_screenshot', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('ic3_screenshot', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('reporter_first_name', models.CharField(blank=True, max_length=100)),
                ('reporter_last_name', models.CharField(blank=True, max_length=100)),
                ('reporter_address', models.CharField(blank=True, max_length=200)),
                ('reporter_address2', models.CharField(blank=True, max_length=200)),
                ('reporter_city', models.CharField(blank=True, max_length=100)),
                ('reporter_state', models.CharField(blank=True, max_length=100)),
                ('reporter_zip', models.CharField(blank=True, max_length=20)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('resporg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.resporg')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scam_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('resporg_lookup', 'RespOrg Lookup'), ('email_sent', 'Email Sent'), ('status_changed', 'Status Changed'), ('screenshot_saved', 'Screenshot Saved')], max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reports.scamreport')),
            ],
            options={
                'db_table': 'report_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
