# Generated by Django 6.0.4 on 2026-04-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='ic3_screenshot_b64',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
