# Generated by Django 6.0.4 on 2026-04-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_scamreport_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='ftc_screenshot',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='ic3_screenshot',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
