# Generated by Django 6.0.4 on 2026-05-01 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_scamreport_ic3_screenshot_b64'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('abuse_complaint', 'Abuse Complaint'), ('ftc_report', 'FTC Report'), ('ic3_report', 'IC3 Report'), ('carrier_abuse', 'Carrier Abuse')], max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('cc_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('subject', models.CharField(max_length=500)),
                ('body_preview', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='reports.scamreport')),
            ],
            options={
                'db_table': 'sent_email',
                'ordering': ['-sent_at'],
            },
        ),
    ]
