# Generated by Django 6.0.4 on 2026-04-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_scamreport_ftc_screenshot_scamreport_ic3_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamreport',
            name='ftc_screenshot',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='ic3_screenshot',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
