# Generated by Django 6.0.4 on 2026-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_scamreport_ftc_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter_address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
