services:
  - type: web
    name: fraudhunter-api
    env: docker
    rootDir: Back-end
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: fraudhunter-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: fraudhunter-redis
          type: psc
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "fraudhunter-api.onrender.com,api.fraudhunter.net"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://www.fraudhunter.net,https://fraudhunter.net,https://fraudhunter-frontend.vercel.app"
      - key: SCAM_SLAYER_API_KEY
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: IPQS_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.resend.com"
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_USE_SSL
        value: "True"
      - key: EMAIL_USE_TLS
        value: "False"
      - key: EMAIL_HOST_USER
        value: "resend"
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "FraudHunter <reports@fraudhunter.net>"
      - key: RESPORG_BACKEND
        value: "local"

  - type: psc
    name: fraudhunter-redis
    plan: starter

databases:
  - name: fraudhunter-db
    plan: free        